#!/bin/bash

# Start nginx in the background
# sudo nginx &
# Start Gunicorn server
# exec gunicorn --bind 0.0.0.0:8080 wsgi:application


set -e

# Start Gunicorn in the background
exec gunicorn --bind unix:/tmp/gunicorn.sock -w 1 wsgi:app &

# Start Nginx
exec nginx -c /etc/nginx/nginx.conf
